# Site settings
title: Bioinformatics Journal Club
email: 
description: > # this means to ignore newlines until "baseurl:"
   A course at the University of Michigan introducing students
    to journal articles and presentations in Bioinformatics.
baseurl: "https://dcmb-courses.github.io/bioinf602-603-fall2020" # the subpath of your site, e.g. /blog/
url: "https://dcmb-courses.github.io/bioinf602-603-fall2020" 
twitter_username: 
github_username: 

# Build settings
markdown: kramdown

